version: "3.9"
services: 
  mysqldb:
    image: mysql:8.0.28-oracle
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=eoloplantsDB
    network_mode: "host" 
  
  mongodb:
    image: mongo:4.2.8
    environment:
      - MONGO_INITDB_DATABASE=topo
    network_mode: "host" 
  
  rabbitmq:
    image: rabbitmq:3-management
    network_mode: "host" 
