version: "3.9"
services: 
  server:
    image: luisb493/server:latest
    ports:
      - "3000:3000"
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
      - DB_USER=root
      - DB_PASS=my-secret-pass
      - MYSQLHOST=mysqldb
    depends_on:
      - rabbitmq
      - mysqldb
    command: [ "./wait-for-it.sh", "mysqldb:3306", "-t", "120" , "--", "node", "./src/server.js" ]
  
  planner:
    image: luisb493/planner:latest
    environment:
      - GRPC_CLIENT_WEATHERSERVER_ADDRESS=static://weatherservice:9090
      - SPRING_CLOUD_STREAM_RABBIT_BINDER_NODES=guest:guest@rabbitmq:5672
      - RABBITMQ_NODE_IP_ADDRESS=rabbitmq
      - SPRING_RABBITMQ_HOST=rabbitmq
      - TOPO_CLIENT_ADDRESS=toposervice:8181
    depends_on:
      - rabbitmq
      - weatherservice
      - toposervice
  
  weatherservice:
    image: luisb493/weatherservice:latest
    ports:
      - "9090:9090"
  
  toposervice:
    image: luisb493/toposervice:latest
    ports:
      - "8181:8181"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=topo
    depends_on:
      - mongodb
  
  mysqldb:
    image: mysql:8.0.28-oracle
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pass
      - MYSQL_DATABASE=eoloplantsDB
      - MYSQL_USER=admin99,
      - MYSQL_PASSWORD=password
    expose:
      - "3306"
    volumes:
      - ./mysql:/var/lib/mysql
  
  mongodb:
    image: mongo:4.2.8
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=topo
    volumes:
      - ./mongo:/data/db
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
    expose:
      - "5672"
