version: "3.9"
services: 
  server:
    image: luisb493/server
    ports:
      - "3000:3000"
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
      - DB_USER="root"
      - DB_PASS="password"
  planner:
    image: luisb493/planner
    environment:
      - GRPC_CLIENT_WEATHERSERVER_ADDRESS=static://weatherservice:9090
      - SPRING_CLOUD_STREAM_RABBIT_BINDER_NODES=rabbitmq:5672
  weatherservice:
    image: luisb493/weatherservice
    ports:
      - "9090:9090"
  toposervice:
    image: luisb493/toposervice
    ports:
      - "8181:8181"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=topo
  mysqldb:
    image: mysql:8.0.28
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=eoloplantsDB
    volumes:
      - ./mysql:/var/lib/mysql
  mongodb:
    image: mongo:4.2.8
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=topo
    volumes:
      - ./mongo:/data/db
  rabbitmq:
    image: rabbitmq:3.7.8
    ports:
      - "5672:5672"
