version: "3.9"
services: 
  mysqldb:
    image: mysql:8.0.28-oracle
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=eoloplantsDB
    #network_mode: host
    expose:
      - 3306
    ports:
      - 3306:3306
  
  mongodb:
    image: mongo:4.2.8
    environment:
      - MONGO_INITDB_DATABASE=topo
    #network_mode: host
    expose:
      - 27017
    ports:
      - 27017:27017
  
  rabbitmq:
    image: rabbitmq:3-management
    #network_mode: host
    expose:
      - 5672
      - 15672
    ports:
      - 5672:5672
      - 15672:15672
