apiVersion: networking.k8s.io/v1
kind: Ingress  
metadata:  
  name: eoloplants-ingress
spec:  
  rules:
   - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: server-service
            port:
              number: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress  
metadata:  
  name: toposervice-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:  
  rules:
   - http:
      paths:    
      - path: /toposervice(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: toposervice-service
            port:
              number: 8181
            