---
{{- $fullName := include "eoloplants.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-mongodb-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ $fullName }}-mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ $fullName }}-mongodb
    spec:
      containers:
      - name: {{ $fullName }}-mongodb
        image: {{ .Values.images.mongo.repository }}:{{ .Values.images.mongo.tag }} 
        imagePullPolicy: {{ .Values.images.mongo.pullPolicy }}
        env:
        - name: MONGO_INITDB_DATABASE
          value: topoDB
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 27017
        - containerPort: 27018
        - containerPort: 27019
        volumeMounts:
        - mountPath: /data/db
          name: {{ $fullName }}-datadb
      volumes:
      - name: {{ $fullName }}-datadb
        persistentVolumeClaim:
          claimName: {{ $fullName }}-mongo-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-mongo-pvc
spec:
  storageClassName: {{ $fullName }}-mongo
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi          
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-mongodb-service
  labels:
    app: {{ $fullName }}-mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: {{ $fullName }}-mongodb-port-27017
  - port: 27018
    targetPort: 27018
    protocol: TCP
    name: {{ $fullName }}-mongodb-port-27018
  - port: 27019
    targetPort: 27019
    protocol: TCP
    name: {{ $fullName }}-mongodb-port-27019
  selector:
    app: {{ $fullName }}-mongodb
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $fullName }}-mongodb-from-topo
spec:
  podSelector:
    matchLabels:
      app: {{ $fullName }}-mongodb
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ $fullName }}-toposervice
    ports:
    - port: 27017
      protocol: TCP
