{{- $fullName := include "eoloplants.fullname" . -}}
{{- $useExistingVolume := (.Values.persistence.useExistingVolumes) -}}
{{- if not $useExistingVolume -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $fullName }}-mysql-pv
spec:
  storageClassName: {{ $fullName }}-mysql
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /{{ $fullName }}/db/mysql
{{- end -}}