{{- $fullName := include "eoloplants.fullname" . -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $fullName }}-rabbit-pv
spec:
  storageClassName: {{ $fullName }}-rabbit
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /db/rabbitmq