---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: codeurjc/server:v1.0
        env:
        - name: MYSQL_HOST
          value: mysql       
        - name: MYSQL_DB
          value: eoloplantsDB   
        - name: MYSQL_USER
          value: root   
        - name: MYSQL_PASS
          value: password   
        - name: RABBITMQ_URL
          value: amqp://root:password@rabbitmq   

---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  type: LoadBalancer
  selector:
    app: server
  ports:
  - port: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.28
        env:
        - name: MYSQL_DATABASE
          value: eoloplantsDB    
        - name: MYSQL_ROOT_PASSWORD
          value: password  
        
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - port: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.9-management
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: root    
        - name: RABBITMQ_DEFAULT_PASS
          value: password  
        
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
  - port: 5672
    name: rabbit-port
  - port: 15672
    name: rabbit-management-plugin

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherservice
spec:
  selector:
    matchLabels:
      app: weatherservice
  template:
    metadata:
      labels:
        app: weatherservice
    spec:
      containers:
      - name: weatherservice
        image: codeurjc/weatherservice:v1.0
        env:
        - name: GRPC_HOST
          value: weatherservice   
        - name: GRPC_PORT
          value: "9090"
        
---
apiVersion: v1
kind: Service
metadata:
  name: weatherservice
  labels:
    app: weatherservice
spec:
  type: ClusterIP
  selector:
    app: weatherservice
  ports:
  - port: 9090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toposervice
spec:
  selector:
    matchLabels:
      app: toposervice
  template:
    metadata:
      labels:
        app: toposervice
    spec:
      containers:
      - name: toposervice
        image: codeurjc/toposervice:v1.0
        env:
        - name: SPRING_DATA_MONGODB_HOST
          value: mongodb
        - name: SPRING_DATA_MONGODB_PORT
          value: "27017"
        - name: SPRING_DATA_MONGODB_DATABASE
          value: topoDB
        - name: SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE
          value: admin
        - name: SPRING_DATA_MONGODB_USERNAME
          value: root
        - name: SPRING_DATA_MONGODB_PASSWORD
          value: password
        
---
apiVersion: v1
kind: Service
metadata:
  name: toposervice
  labels:
    app: toposervice
spec:
  type: ClusterIP
  selector:
    app: toposervice
  ports:
  - port: 8181

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0.6-focal
        env:
        - name: MONGO_INITDB_DATABASE
          value: topoDB
        - name: MONGO_INITDB_ROOT_USERNAME 
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD 
          value: password
        
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - port: 27017

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planner
spec:
  selector:
    matchLabels:
      app: planner
  template:
    metadata:
      labels:
        app: planner
    spec:
      containers:
      - name: planner
        image: codeurjc/planner:v1.0
        env:
        # Enviroment variables for connect to TopoService
        - name: TOPO_HOST
          value: toposervice
        - name: TOPO_PORT
          value: "8181"
        # Enviroment variables for connect to WeatherService
        - name: GRPC_CLIENT_WEATHERSERVER_ADDRESS
          value: static://weatherservice:9090
        # Enviroment variables for connect to RabbitMQ
        - name: SPRING_CLOUD_STREAM_RABBIT_BINDER_NODES
          value: rabbitmq:5672
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          value: root
        - name: SPRING_RABBITMQ_PASSWORD
          value: password
        - name: SERVER_PORT
          value: "3000"
        