---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: codeurjc/server:v1.0
        env:
        - name: MYSQL_HOST
          value: mysql       
        - name: MYSQL_DB
          value: eoloplantsDB   
        - name: MYSQL_USER
          value: root   
        - name: MYSQL_PASS
          value: password   
        - name: RABBITMQ_URL
          value: amqp://root:password@rabbitmq   

---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  type: LoadBalancer
  selector:
    app: server
  ports:
  - port: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.28
        env:
        - name: MYSQL_DATABASE
          value: eoloplantsDB    
        - name: MYSQL_ROOT_PASSWORD
          value: password  
        
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - port: 3306

  ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.9-management
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: root    
        - name: RABBITMQ_DEFAULT_PASS
          value: password  
        
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
  - port: 5672
  - port: 15672